/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.archive.jsonc --include-runtime=false --strict-vars=false --env-interface=ArchiveEnv workers/archive/env.d.ts` (hash: faffc8bc70fcd8c2600842d4789fa80b)
interface __BaseEnv_ArchiveEnv {
	RAW: R2Bucket;
	INDEX: D1Database;
	ARCHIVE_ENABLED: string;
	BACKFILL_DAYS: string;
	ARCHIVE_MIN_INTERVAL_MS: string;
	ARCHIVE_SLOT_WINDOW_MS: string;
	ARCHIVE_REQUEST_TIMEOUT_MS: string;
	ARCHIVE_REQUEST_LEASE_MS: string;
	ARCHIVE_RETRY_WAIT_MS: string;
	ARCHIVE_MAX_BODY_BYTES: string;
	ARCHIVE_DISPLAY_TIMES: string;
	ARCHIVE_MAX_PAGES: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ArchiveEnv {}
}
interface ArchiveEnv extends __BaseEnv_ArchiveEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ARCHIVE_ENABLED" | "BACKFILL_DAYS" | "ARCHIVE_MIN_INTERVAL_MS" | "ARCHIVE_SLOT_WINDOW_MS" | "ARCHIVE_REQUEST_TIMEOUT_MS" | "ARCHIVE_REQUEST_LEASE_MS" | "ARCHIVE_RETRY_WAIT_MS" | "ARCHIVE_MAX_BODY_BYTES" | "ARCHIVE_DISPLAY_TIMES" | "ARCHIVE_MAX_PAGES">> {}
}
