/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.archive.jsonc --include-runtime=false --strict-vars=false --env-interface=ArchiveEnv workers/archive/env.d.ts` (hash: 8260a62a607c3a1c529cd4c86e743f42)
interface __BaseEnv_ArchiveEnv {
	RAW: R2Bucket;
	INDEX: D1Database;
	ARCHIVE_ENABLED: string;
	BACKFILL_DAYS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ArchiveEnv {}
}
interface ArchiveEnv extends __BaseEnv_ArchiveEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ARCHIVE_ENABLED" | "BACKFILL_DAYS">> {}
}
