"""Inspect tracked/staged files, never print matched secret contents."""

from pathlib import Path
import re
import subprocess
import sys

FORBIDDEN_PARTS = {"private", "data", "outputs", ".venv", "node_modules", ".wrangler"}
DATA_SUFFIXES = {".zip", ".csv", ".parquet", ".sqlite", ".db", ".pem", ".key"}
SECRETS = [
    re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(rb"gh[pousr]_[A-Za-z0-9]{30,}"),
    re.compile(rb'(?i)(?:api[_-]?token|password|secret)\s*[=:]\s*["\x27][A-Za-z0-9_+/=-]{24,}["\x27]'),
]


def audit(root, paths, blobs=None, symlinks=()):
    errors = []
    for name in paths:
        path = Path(name)
        if set(path.parts) & FORBIDDEN_PARTS or path.name.startswith((".env", ".dev.vars")):
            errors.append((name, "private path"))
            continue
        if path.suffix.lower() in DATA_SUFFIXES:
            errors.append(
                (name, "data or key file; synthetic files must be generated by reviewed fixture code")
            )
            continue
        full = Path(root) / path
        if name in symlinks or (blobs is None and full.is_symlink()):
            errors.append((name, "symlink"))
            continue
        if blobs is None and not full.is_file():
            continue
        data = blobs[name] if blobs is not None else full.read_bytes()
        if any(pattern.search(data) for pattern in SECRETS):
            errors.append((name, "credential pattern"))
    return errors


def audit_index(root):
    entries = subprocess.check_output(["git", "ls-files", "--stage", "-z"], cwd=root).split(b"\0")
    blobs, symlinks = {}, []
    for entry in entries:
        if not entry:
            continue
        metadata, name = entry.split(b"\t", 1)
        mode, digest, stage = metadata.decode().split()
        path = name.decode()
        if stage != "0":
            return [(path, "unmerged index")]
        blobs[path] = subprocess.check_output(["git", "cat-file", "blob", digest], cwd=root)
        if mode == "120000":
            symlinks.append(path)
    return audit(root, list(blobs), blobs, symlinks)


if __name__ == "__main__":
    names = subprocess.check_output(["git", "ls-files", "-z"], text=True).split("\0")
    errors = audit_index(Path.cwd()) + audit(Path.cwd(), [x for x in names if x])
    for path, reason in sorted(set(errors)):
        print(f"{path}: {reason}", file=sys.stderr)
    if errors:
        sys.exit(1)
    print("Public boundary: Git index and working tree passed; no data values printed.")
